export const PLUGIN_ID = "dateline-core";
export const PLUGIN_VERSION = "0.1.0";
export const EVENTS_COLLECTION = "dateline_events";
export const VENUES_COLLECTION = "dateline_venues";
export const ORGANIZERS_COLLECTION = "dateline_organizers";
export const ATTENDEES_COLLECTION = "dateline_attendees";
export const CACHE_TTL_SECONDS = 300;
export const JSON_HEADERS = { "content-type": "application/json; charset=utf-8" };
export const ICAL_HEADERS = { "content-type": "text/calendar; charset=utf-8" };
export const TOMBSTONED_EMAIL = "erased@dateline.local";
