export const PLUGIN_ID = "dateline-importer";
export const PLUGIN_VERSION = "0.1.0";
export const EVENTS_COLLECTION = "dateline_events";
export const JSON_HEADERS = { "content-type": "application/json; charset=utf-8" };
export const IMPORTER_CRON_NAME = "dateline-importer-scheduled-imports";
export const IMPORTER_CRON_SCHEDULE = "*/15 * * * *";
export const MAX_REMOTE_SUBREQUESTS = 10;
export const REMOTE_FETCH_TIMEOUT_MS = 25_000;
export const DEFERRED_STATUS_PENDING = "pending";
export const DEFERRED_STATUS_COMPLETED = "completed";
export const DEFERRED_STATUS_FAILED = "failed";
